/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVpnRouteImport } from './routes/_app.vpn'
import { Route as AppSupportAiRouteImport } from './routes/_app.support-ai'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMyVpnRouteImport } from './routes/_app.my-vpn'
import { Route as AppFaqRouteImport } from './routes/_app.faq'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as ApiPublicSubTokenRouteImport } from './routes/api/public/sub.$token'
import { Route as ApiPublicSbSplatRouteImport } from './routes/api/public/sb.$'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVpnRoute = AppVpnRouteImport.update({
  id: '/vpn',
  path: '/vpn',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportAiRoute = AppSupportAiRouteImport.update({
  id: '/support-ai',
  path: '/support-ai',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMyVpnRoute = AppMyVpnRouteImport.update({
  id: '/my-vpn',
  path: '/my-vpn',
  getParentRoute: () => AppRoute,
} as any)
const AppFaqRoute = AppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSubTokenRoute = ApiPublicSubTokenRouteImport.update({
  id: '/api/public/sub/$token',
  path: '/api/public/sub/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSbSplatRoute = ApiPublicSbSplatRouteImport.update({
  id: '/api/public/sb/$',
  path: '/api/public/sb/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/faq': typeof AppFaqRoute
  '/my-vpn': typeof AppMyVpnRoute
  '/profile': typeof AppProfileRoute
  '/support': typeof AppSupportRoute
  '/support-ai': typeof AppSupportAiRoute
  '/vpn': typeof AppVpnRoute
  '/api/public/sb/$': typeof ApiPublicSbSplatRoute
  '/api/public/sub/$token': typeof ApiPublicSubTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/faq': typeof AppFaqRoute
  '/my-vpn': typeof AppMyVpnRoute
  '/profile': typeof AppProfileRoute
  '/support': typeof AppSupportRoute
  '/support-ai': typeof AppSupportAiRoute
  '/vpn': typeof AppVpnRoute
  '/api/public/sb/$': typeof ApiPublicSbSplatRoute
  '/api/public/sub/$token': typeof ApiPublicSubTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/faq': typeof AppFaqRoute
  '/_app/my-vpn': typeof AppMyVpnRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/support-ai': typeof AppSupportAiRoute
  '/_app/vpn': typeof AppVpnRoute
  '/api/public/sb/$': typeof ApiPublicSbSplatRoute
  '/api/public/sub/$token': typeof ApiPublicSubTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/faq'
    | '/my-vpn'
    | '/profile'
    | '/support'
    | '/support-ai'
    | '/vpn'
    | '/api/public/sb/$'
    | '/api/public/sub/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/faq'
    | '/my-vpn'
    | '/profile'
    | '/support'
    | '/support-ai'
    | '/vpn'
    | '/api/public/sb/$'
    | '/api/public/sub/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/faq'
    | '/_app/my-vpn'
    | '/_app/profile'
    | '/_app/support'
    | '/_app/support-ai'
    | '/_app/vpn'
    | '/api/public/sb/$'
    | '/api/public/sub/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicSbSplatRoute: typeof ApiPublicSbSplatRoute
  ApiPublicSubTokenRoute: typeof ApiPublicSubTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vpn': {
      id: '/_app/vpn'
      path: '/vpn'
      fullPath: '/vpn'
      preLoaderRoute: typeof AppVpnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support-ai': {
      id: '/_app/support-ai'
      path: '/support-ai'
      fullPath: '/support-ai'
      preLoaderRoute: typeof AppSupportAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-vpn': {
      id: '/_app/my-vpn'
      path: '/my-vpn'
      fullPath: '/my-vpn'
      preLoaderRoute: typeof AppMyVpnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faq': {
      id: '/_app/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AppFaqRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/sub/$token': {
      id: '/api/public/sub/$token'
      path: '/api/public/sub/$token'
      fullPath: '/api/public/sub/$token'
      preLoaderRoute: typeof ApiPublicSubTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sb/$': {
      id: '/api/public/sb/$'
      path: '/api/public/sb/$'
      fullPath: '/api/public/sb/$'
      preLoaderRoute: typeof ApiPublicSbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppFaqRoute: typeof AppFaqRoute
  AppMyVpnRoute: typeof AppMyVpnRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSupportRoute: typeof AppSupportRoute
  AppSupportAiRoute: typeof AppSupportAiRoute
  AppVpnRoute: typeof AppVpnRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppFaqRoute: AppFaqRoute,
  AppMyVpnRoute: AppMyVpnRoute,
  AppProfileRoute: AppProfileRoute,
  AppSupportRoute: AppSupportRoute,
  AppSupportAiRoute: AppSupportAiRoute,
  AppVpnRoute: AppVpnRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicSbSplatRoute: ApiPublicSbSplatRoute,
  ApiPublicSubTokenRoute: ApiPublicSubTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
